### ISSUE TITLE
Add integration with, e.g., Travis CI

### ISSUE THREAD

**Issue by adamml** [IrishMarineInstitute/awesome-erddap#10]

**Comment by adamml** [comment]
Added with 029d7efcfe7628eeddedf8fa23e332e5a5cb8569, d6c833d208bd03fcefeb2726aa873988169838a2 and 458887cc3f24df951c59f7f936a5c0b887972031 but hitting a GitHub API rate limit, so now need to figure out adding a token to get the rate limit up.

**Comment by adamml** [comment]
Now the build is passing using a GitHub PAT.

The next stage is to get it to recommit to the branch following the build.

**Comment by adamml** [comment]
switched the build and test process to GitHub Actions with 9f836e4250a3f4a30a5db2b506604223ac38334a, 004f14cfc4c3e9fefc1c76de3971fc465da51e74, 72bb3c6580471eee3ed7e64a605bd90eb7e0de6b and f38318a39e187b4d590541d519cd64fd2b8939d1.

However, this required temporarily dropping the Awesome Linter as it was complaining about the age of the repo.

Still require recommitting of the erddaps.js file as well.

**Comment by adamml** [comment]
Needs testing, but should be sorted now with 8b7ea3713075bb3904d3d3891af1f55f6c707781

**Comment by fullergalway** [comment]
Working again after adding package-lock.json back into the mix.
